# Generated by Django 3.2 on 2021-04-24 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('television', 'Television'), ('refrigerator', 'Female')], max_length=50)),
                ('model_no', models.CharField(max_length=50, unique=True)),
                ('availability_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('added_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
