# Generated by Django 3.2 on 2021-04-24 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('order_details', models.TextField()),
                ('order_time', models.DateTimeField(default=datetime.datetime.now)),
                ('customer_details', models.TextField()),
                ('delivery_dist', models.IntegerField()),
                ('delivery_eta', models.DateTimeField(blank=True)),
            ],
        ),
    ]
