# Generated by Django 3.2 on 2021-04-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
