# Generated by Django 3.2 on 2021-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'CONFIRMED'), ('processing', 'PROCESSING'), ('in-transit', 'IN-TRANSIT'), ('delivered', 'DELIVERED')], default='confirmed', max_length=50),
        ),
    ]
